version: '3.1'
services:
  nextjs:
    #image: "nextjs-boilerplate:latest"
    build:
      context: .
      target: nextjs
      args:
        BUILD_TYPE: prod-dynamic
        #BUILD_TYPE: prod-static
        #NODE_VERSION: current-alpine
        #NODE_VERSION: current
        HTTPD_VERSION: 2.4
    restart: unless-stopped
    ports:
      - 9000:9000
