name: Cypress Chrome on Ubuntu 20.04

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    strategy:
      matrix:
        node: [14, 16, 17]
    name: E2E Chrome on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node -v
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: false
          tag: node-${{ matrix.node }}
          group: Chrome Tests on Node v${{ matrix.node }}
          cache-key: node-v${{ matrix.node }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
          browser: chrome
          build: yarn run build
          start: yarn run start
          wait-on: 'http://localhost:9000'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos